datastore:
    image: busybox
    volumes:
        - /opt/django-app/psql:/var/lib/postgresql/data

db:
    image: erroneousboat/postgres
    volumes_from:
        - datastore
    env_file:
        - config/environment/env

app:
    build: .
    volumes:
        - code:/srv/django
    ports:
        - "9080:80"
        - "9443:443"
    links:
        - db
    env_file:
        - config/environment/env