datastore:
    image: busybox
    volumes:
        - /opt/django-app/psql:/var/lib/postgresql/data

db:
    image: erroneousboat/postgres
    volumes_from:
        - datastore
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=mysecretpassword

app:
    build: .
    volumes:
        - code:/srv/django
    ports:
        - "9080:80"
        - "9443:443"
    links:
        - db
    environment:
        - POSTGRES_HOST=db
        - POSTGRES_NAME=database
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_PORT=5432
        - DJANGO_PROJECT_NAME=starter
        - NGINX_SERVER_NAME=localhost
        - NGINX_CRT_NAME
        - NGINX_KEY_NAME